# Generated by Django 3.2.7 on 2024-08-13 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 2, 33, 48, 882960, tzinfo=utc)),
        ),
    ]
