# Generated by Django 3.2.7 on 2024-08-13 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
