# Generated by Django 3.2.7 on 2024-08-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_managers_message_translated_body_and_more'),
        ('base', '0009_auto_20240813_0443'),
    ]

    operations = [
    ]
